POST http://localhost:6969/revPosts/create HTTP/1.1
Content-Type: application/json

{
    "title": "titolo 1",
    "description": "description of 15+ characters",
    "user": "64f844d994a234292f5ba5fb"
}

########
GET http://localhost:6969/revPosts

#####
GET http://localhost:6969/revPosts?page=2

#####
GET http://localhost:6969/revPosts/title?postTitle=titolo

#####
GET http://localhost:6969/revPosts/byNickname?userNickname=Mistiko009

#####
PATCH http://localhost:6969/revPost/64f216a313294dcda14f763d
Content-Type: application/json

{
    "likes": 10
}

#####
DELETE http://localhost:6969/revPost/64ef8ef8e92b514e6afe0cd8