POST http://localhost:6969/revPosts/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFyY2VsbG8gIiwic3VybmFtZSI6IlBhc3RvcmUgIiwiZW1haWwiOiJtYXJjZWxsb3Bhc3RvcmU0QGdtYWlsLmNvbSIsImFnZSI6MjEsIm5pY2tuYW1lIjoiWk9QIE1pc3Rpa28iLCJpYXQiOjE2OTQ5NzIxNDcsImV4cCI6MTY5NTA1ODU0N30.1W9S3xNRjB-04iuzeNXjsyqauECn-9aTpGGPQEszFE0

{
    "title": "titolo 2",
    "img1": "IMMAGINE 2",
    "description": "description of 15+ characters",
    "user": "6507237cd4385a7b50cc22ef"
}

########
GET http://localhost:6969/revPosts

#####
GET http://localhost:6969/revPosts?page=2

#####
GET http://localhost:6969/revPosts/title?postTitle=titolo

#####
GET http://localhost:6969/revPosts/byNickname?userNickname=Mistiko009

#####
PATCH http://localhost:6969/revPost/64f216a313294dcda14f763d
Content-Type: application/json

{
    "likes": 10
}

#####
DELETE http://localhost:6969/revPost/65002aeedef869665c07e82c

#####
POST http://localhost:6969/revPost/65002aeedef869665c07e82c/comments HTTP/1.1
Content-Type: application/json

{
    "user": "65002ae3def869665c07e82a",
    "content": "Primo commento del post",
    "postTd": "65002aeedef869665c07e82c"
}
#####
GET http://localhost:6969/revPost/65002aeedef869665c07e82c
