GET http://localhost:6969/users

#####
GET http://localhost:6969/users/64f2094f471a68bce92ce26c

#####
GET http://localhost:6969/user/byNickname?userNickname=Mistiko009

#####
POST http://localhost:6969/user/create HTTP/1.1
Content-Type: application/json

{
    "name": "Marcello ",
    "surname": "Pastore ",
    "age": 21,
    "email": "marcellopastore4@gmail.com",
    "nickname": "ZOP Mistiko",
    "password": "mko009"
}

#####
PATCH http://localhost:6969/user/64ef8ba0039737b60c1e9d67
Content-Type: application/json

{
    "name": "Pippo",
    "surname": "Ciccio",
    "age": 69,
    "email": "pippoCiccio@gmail.com",
    "nickname": "Pippos69",
    "password": "pippociccio99"
}

#####
DELETE http://localhost:6969/user/650568f551a54806dc542c8c